services:
  - type: web
    name: ballot-usa-backend
    env: node
    plan: free
    buildCommand: |
      mkdir -p /opt/render/project/build
      cp -r server/* /opt/render/project/build/
      cd /opt/render/project/build
      npm install
    startCommand: |
      cd /opt/render/project/build
      node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        generateValue: true
      - key: PG_HOST
        fromDatabase:
          name: ballot-db
          property: host
      - key: PG_PORT
        fromDatabase:
          name: ballot-db
          property: port
      - key: PG_USER
        fromDatabase:
          name: ballot-db
          property: user
      - key: PG_PASS
        fromDatabase:
          name: ballot-db
          property: password
      - key: PG_DB
        fromDatabase:
          name: ballot-db
          property: database

databases:
  - name: ballot-db
    databaseName: ballot
    plan: free
